"""Add PWD completion fields to issues

Revision ID: b10012f06354
Revises: 17a46ad63e86
Create Date: 2026-01-01 00:25:00.895007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b10012f06354'
down_revision: Union[str, Sequence[str], None] = '17a46ad63e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('completion_description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('issues', sa.Column('completion_photo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('issues', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issues', sa.Column('completed_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_issues_completed_by_id'), 'issues', ['completed_by_id'], unique=False)
    op.create_foreign_key(None, 'issues', 'users', ['completed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_index(op.f('ix_issues_completed_by_id'), table_name='issues')
    op.drop_column('issues', 'completed_by_id')
    op.drop_column('issues', 'completed_at')
    op.drop_column('issues', 'completion_photo_url')
    op.drop_column('issues', 'completion_description')
    # ### end Alembic commands ###
